/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.GUI;

import com.mycompany.roulette.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Map;
import javax.print.attribute.AttributeSet;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author bobvo
 */
public class Mesa extends javax.swing.JFrame {
    private Timer timer;
    private BetHandler betHandler;
    private DefaultTableModel table;
    private Table mesa;
    private Player currentPlayer;

    /**
     * Creates new form Table
     */
    public Mesa() {
        initComponents();
        betHandler = new BetHandler();
        mesa = new Table();
        btnStartGame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlayer = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAddPlayer = new javax.swing.JButton();
        lblCurrentPlayer = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablero ruleta 02_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnStartGame.setText("START GAME");
        btnStartGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartGameMouseClicked(evt);
            }
        });
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COLOR MAS FRECUENTE: ");

        tablePlayer.setAutoCreateRowSorter(true);
        tablePlayer.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Nombre", "Creditos", "Apuesta(s)"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tablePlayer.setColumnSelectionAllowed(true);
        tablePlayer.setMaximumSize(new java.awt.Dimension(555, 111));
        tablePlayer.setMinimumSize(new java.awt.Dimension(225, 16));
        tablePlayer.setPreferredSize(new java.awt.Dimension(555, 111));
        jScrollPane1.setViewportView(tablePlayer);
        tablePlayer.getColumnModel().getSelectionModel()
                .setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tablePlayer.getColumnModel().getColumnCount() > 0) {
            tablePlayer.getColumnModel().getColumn(0).setResizable(false);
        }
        tablePlayer.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jugadores Registrados");

        btnAddPlayer.setText("ADD PLAYER");
        btnAddPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPlayerMouseClicked(evt);
            }
        });

        lblCurrentPlayer.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblCurrentPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrentPlayer.setText("JUGADOR : ");

        lblTimer.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblTimer.setText("Le quedan : 00(min):00(seg)");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ESTADISTICAS");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NUMERO MAS FRECUENTE:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel2");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JUGADOR CON MAS GANANCIAS : ");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JUGADOR CON MAYORES PERDIDAS : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(lblTimer,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        270,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(48, 48, 48))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(btnAddPlayer,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                141,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(18, 18, 18)))
                                                                .addComponent(btnStartGame,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblCurrentPlayer,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 205,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(131, 131, 131)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel7,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 309,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(45, 45, 45))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addGap(59, 59, 59)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(lblCurrentPlayer))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblTimer)
                                                .addGap(71, 71, 71)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnAddPlayer,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnStartGame,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 54,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        betHandler.clasificarApuesta(x, y, currentPlayer);
        siguienteTurno();
    }// GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        jLabel6.setText("x : " + x + " y: " + y);
    }// GEN-LAST:event_jLabel1MouseMoved

    private void btnStartGameMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnStartGameMouseClicked
        siguienteTurno();

        if (btnStartGame.getText() == "END GAME") {
            btnStartGame.setText("START GAME");
            timer.stop();
            lblTimer.setText("Le quedan : 00(seg)");
        } else {
            // hidde button btnStartGame
            btnStartGame.setVisible(false);
            btnAddPlayer.setVisible(false);
        }

    }// GEN-LAST:event_btnStartGameMouseClicked

    private void siguienteTurno() {
        updateUserTable();
        currentPlayer = mesa.endGameTurn();

        if (currentPlayer == null) {
            timer.stop();
            mesa.startGame();
            updateUserTable();
        } else {
            lblCurrentPlayer.setText("JUGADOR : " + currentPlayer.name);
            timer = new Timer(1000, new ActionListener() {
                int tiempoRestante = 30;

                public void actionPerformed(ActionEvent e) {
                    this.tiempoRestante--;
                    if (tiempoRestante >= 0) {
                        String tiempoFormateado = String.format(
                                "Al jugador le quedan: %02d(seg)",
                                tiempoRestante % 60);
                        lblTimer.setText(tiempoFormateado);
                    } else {
                        lblTimer.setText("Tiempo agotado");
                        timer.stop();
                        siguienteTurno();
                    }
                }
            });

            timer.start();
            updateUserTable();
        }
    }

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnStartGameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnStartGameActionPerformed

    private void btnAddPlayerMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnAddPlayerMouseClicked
        // TODO add your handling code here:
        abrirFormularioRegistro();
    }// GEN-LAST:event_btnAddPlayerMouseClicked

    private void abrirFormularioRegistro() {
        JDialog registroDialog = new JDialog(this, "Registro de Jugador", true);
        registroDialog.setSize(400, 150);
        registroDialog.setLayout(null);

        JLabel lblNombre = new JLabel("Nombre del Jugador:");
        lblNombre.setBounds(20, 20, 150, 20);
        JTextField txtNombre = new JTextField();
        txtNombre.setBounds(170, 20, 100, 20);

        JLabel lblCreditos = new JLabel("Créditos:");
        lblCreditos.setBounds(20, 50, 150, 20);
        JTextField txtCreditos = new JTextField();
        txtCreditos.setBounds(170, 50, 100, 20);

        JButton btnRegistrar = new JButton("Registrar");
        btnRegistrar.setBounds(120, 80, 100, 30);
        btnRegistrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtén el nombre y créditos ingresados por el jugador
                String nombre = txtNombre.getText();
                float creditos = Float.parseFloat(txtCreditos.getText());

                // Crea un nuevo jugador y agrégalo a la lista de jugadores
                // Jugador jugador = new Jugador(nombre, creditos);
                // jugadores.add(jugador);
                mesa.addPlayer(nombre, creditos);

                if (mesa.players.size() > 0) {
                    btnStartGame.setVisible(true);
                }

                // String aux = String.valueOf(creditos);
                // String[] datos = { nombre, aux, "Apuesta" };
                // // Agrega los datos del jugador al JTable
                // table = (DefaultTableModel) tablePlayer.getModel();
                // table.addRow(datos);
                // jPanel1.updateUI();

                updateUserTable();

                // Cierra el JDialog de registro
                registroDialog.dispose();
            }
        });

        registroDialog.add(lblNombre);
        registroDialog.add(txtNombre);
        registroDialog.add(lblCreditos);
        registroDialog.add(txtCreditos);
        registroDialog.add(btnRegistrar);

        registroDialog.setVisible(true);
    }

    private void updateUserTable() {
        // Clean table
        table = (DefaultTableModel) tablePlayer.getModel();
        table.setRowCount(0);

        ArrayList<Player> players = mesa.players;

        for (Player player : players) {
            Bet currentBet = player.getCurrentBet();

            String betString = "";

            if (currentBet == null) {
                betString = "No hay apuesta";
            } else {
                betString += currentBet.getType() + " ";
                betString += "Cantidad apostada: " + currentBet.credits + "$";
            }

            String[] datos = { player.name, String.valueOf(player.getCredits()), betString };
            table = (DefaultTableModel) tablePlayer.getModel();
            table.addRow(datos);
            jPanel1.updateUI();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlayer;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentPlayer;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JTable tablePlayer;
    // End of variables declaration//GEN-END:variables
}
