/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.GUI;

/**
 *
 * @author bobvo
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnAddPlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablero ruleta 02_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnStartGame.setText("START GAME");

        jButton1.setText("START BET");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Creditos", "Apuesta(s)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }
        jTable1.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Jugadores Registrados");

        btnAddPlayer.setText("ADD PLAYER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnStartGame, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(jLabel3)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        while (10>2){
            if(betOdd(x,y)){
                break;
            }else if(betEven(x, y)){
                break;
            }else if(betOneTo18(x, y)){
                break;
            }else if(bet19To36(x, y)){
                break;
            }else if(betBlack(x, y)){
                break;
            }else if(betRed(x, y)){
                break;
            }else if(betFirstDozen(x, y)){
                break;
            }else if(betScndDozen(x, y)){
                break;
            }else if(betTrdDozen(x, y)){
                break;
            }else if(betZero(x, y)){
                break;
            }else{
                break;
            }
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked
    
    private boolean betFstRow(int x , int y){
        int ax = 381;
        int ay = 229;
        int gx = 448;
        int gy = 262;
        boolean res = false;
        if(verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Betting in Odds");
        }
        return res;
    }
    
    private boolean betSndRow(int x , int y){
        int ax = 381;
        int ay = 229;
        int gx = 448;
        int gy = 262;
        boolean res = false;
        if(verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Betting in Odds");
        }
        return res;
    }
    
    private boolean betThrdRow(int x , int y){
        int ax = 381;
        int ay = 229;
        int gx = 448;
        int gy = 262;
        boolean res = false;
        if(verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Betting in Odds");
        }
        return res;
    }
    
    private boolean betOdd(int x , int y){
        int ax = 381;
        int ay = 229;
        int gx = 448;
        int gy = 262;
        boolean res = false;
        if(verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Betting in Odds");
        }
        return res;
    }
    
    private boolean betEven(int x , int y){
        int ax = 176;
        int ay = 230;
        int gx = 241;
        int gy = 260;
        boolean res = false;
        if(verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Betting in Evens");
        }
        return res;
    }
    private boolean betRed(int x , int y){
        int ax = 243;
        int ay = 230;
        int gx = 309;
        int gy = 261;
        boolean res = false;
        if(verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Bet on Red");
        }
        return res;
    }
    private boolean betBlack(int x , int y){
        int ax = 313;
        int ay = 230;
        int gx = 378;
        int gy = 261;
        boolean res = false;
        if (verifyBet(ax, ay, gx, gy, x, y)){
            System.out.println("Bet on Black");
        }   
        return res;
    }
    
    private boolean betOneTo18(int x , int y){
        int ax = 105;
        int ay = 230;
        int gx = 172;
        int gy = 261;
        boolean res = false;
        if (verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("apuesta de 1 a 18");
        }   
        return res;
    }
    
    private boolean bet19To36(int x , int y){
        int ax = 451;
        int ay = 230;
        int gx = 516;
        int gy = 261;
        boolean res = false;
        if (verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Betting from 19 to 36");
        }   
        return res;
    }
    private boolean betFirstDozen(int x , int y){
        int ax = 107;
        int ay = 194;
        int gx = 239;
        int gy = 223;
        boolean res = false;
        if (verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("First dozen be");
        }   
        return res;
    }
    
    private boolean betScndDozen(int x , int y){
        int ax = 244;
        int ay = 194;
        int gx = 378;
        int gy = 223;
        boolean res = false;
        if (verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Second Dozen bet");
        }
        return res;
    }
    
    private boolean betTrdDozen(int x , int y){
        int ax = 382;
        int ay = 194;
        int gx = 516;
        int gy = 223;
        boolean res = false;
        if (verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("Third Dozen bet");
        }  
        return res;
    }
    
    private boolean betZero(int x , int y){
        int ax = 56;
        int ay = 49;
        int gx = 103;
        int gy = 189;
        boolean res = false;
        if (verifyBet(ax, ay, gx, gy, x, y)){
            res=true;
            System.out.println("apuesta a Cero");
        }
        return res;
    }
    
    private boolean verifyBet(int xMin , int yMin , int xMax , int yMax , int xr , int yr){
        boolean res = false;
        // Se analiza si el valor real de x , esta entre los parametros de X
        if(xr >= xMin  && xr <= xMax){
            // Se analiza si el valor real de y , esta entre los parametros de Y
            if(yr >= yMin && yr <= yMax){
                res = true;
            }
        }
        return res;
    }
    
    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        jLabel2.setText("x : "+x+" y: "+ y);
    }//GEN-LAST:event_jLabel1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlayer;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
